# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: [ 4.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("devtools", "remotes"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Document package
        run: devtools::document()
        shell: Rscript {0}
      - name: Build package
        run: devtools::build(manual = FALSE)
        shell: Rscript {0}
      - name: Check package
        run: devtools::check(manual = FALSE, error_on = "error")
        shell: Rscript {0}
      - name: Install package
        run: devtools::install(quick = TRUE)
        shell: Rscript {0}
